# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2011-2018 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************
swagger: "2.0"

info:
  title: Umbrella vcloud YAML
  description: Top level YAML file to contain all vcloud openapi schemas
  version: "1.0"

basePath: /cloudapi

schemes:
  - https

paths:
  /branding:
    $ref: "./branding/branding.yaml#/paths/branding"

  /branding/logo:
    $ref: "./branding/branding.yaml#/paths/logo"

  /branding/themes:
    $ref: "./branding/branding.yaml#/paths/themes"

  /extensions/ui:
    $ref: "./extensions/extensions.yaml#/paths/extensions-ui"

  /extensions/ui/{id}:
    $ref: "./extensions/extensions.yaml#/paths/extensions-ui-id"

  /extensions/ui/{id}/plugin:
    $ref: "./extensions/extensions.yaml#/paths/extensions-ui-id-plugin"

  /extensions/ui/{id}/tenants:
    $ref: "./extensions/extensions.yaml#/paths/extensions-ui-id-plugin-tenants"

  /extensions/ui/{id}/tenants/publish:
    $ref: "./extensions/extensions.yaml#/paths/extensions-ui-id-plugin-tenants-publish"

  /extensions/ui/{id}/tenants/unpublish:
    $ref: "./extensions/extensions.yaml#/paths/extensions-ui-id-plugin-tenants-unpublish"

  /extensions/ui/{id}/tenants/publishAll:
    $ref: "./extensions/extensions.yaml#/paths/extensions-ui-id-plugin-tenants-publish-all"

  /extensions/ui/{id}/tenants/unpublishAll:
    $ref: "./extensions/extensions.yaml#/paths/extensions-ui-id-plugin-tenants-unpublish-all"

  /serviceItem:
    $ref: "./services/services.yaml#/paths/service-items"

  /serviceItem/{id}:
    $ref: "./services/services.yaml#/paths/service-item"

  /serviceItem/{id}/tenants:
    $ref: "./services/services.yaml#/paths/service-item-tenants"

  /serviceItem/{id}/tenants/publish:
    $ref: "./services/services.yaml#/paths/service-item-tenants-publish"

  /serviceItem/{id}/tenants/unpublish:
    $ref: "./services/services.yaml#/paths/service-item-tenants-unpublish"

  /serviceItem/{id}/tenants/publishAll:
    $ref: "./services/services.yaml#/paths/service-item-tenants-publish-all"

  /serviceItem/{id}/tenants/unpublishAll:
    $ref: "./services/services.yaml#/paths/service-item-tenants-unpublish-all"

  /serviceLibrary:
    $ref: "./services/services.yaml#/paths/services"

  /serviceLibrary/{id}:
    $ref: "./services/services.yaml#/paths/service"

  #BEGIN temporary codegen placeholder
  #enforce generation of referred VroWorkflowServiceItem
  /serviceLibrary/{id}/workflows:
    $ref: "./services/services.yaml#/paths/workflow-items"

  #enforce generation of referred parameter types
  /workflows/parameterTypes:
    $ref: "./vro/workflowExecution.yaml#/paths/parameter-types"

  #enforce generation of referred presentation elements
  /workflows/presentationElements:
    $ref: "./vro/workflowExecution.yaml#/paths/supported-presentation-elements"

  #enforce generation of referred decorators
  /workflows/decorators:
    $ref: "./vro/workflowExecution.yaml#/paths/supported-decorators"

  #enforce generation of referred constraints
  /workflows/constraints:
    $ref: "./vro/workflowExecution.yaml#/paths/supported-constraints"
  #END temporary codegen placeholder

  /vro/servers:
    $ref: "./vro/vro.yaml#/paths/vros"

  /vro/servers/{id}:
    $ref: "./vro/vro.yaml#/paths/vro"

  /vro/servers/{vroServerId}/workflows:
    $ref: "./vro/vro.yaml#/paths/queryWorkflows"

  /vro/servers/{vroId}/inventory{any:.*}:
    $ref: "./vro/vro.yaml#/paths/vroInventory"

  /vro/servers/{vroId}/catalog:
    $ref: "./vro/vro.yaml#/paths/vroCatalogBase"

  /vro/servers/{vroId}/catalog/{plugin}:
    $ref: "./vro/vro.yaml#/paths/vroCatalogPlugin"

  /vro/servers/{vroId}/catalog/{plugin}/{type}:
    $ref: "./vro/vro.yaml#/paths/vroCatalogPluginType"

  /vro/servers/{vroId}/catalog/{plugin}/{type}/{itemId}:
    $ref: "./vro/vro.yaml#/paths/vroCatalogPluginTypeItem"

  /workflows/{workflowId}/executions:
    $ref: "./vro/workflowExecution.yaml#/paths/workflow-executions"

  /workflows/{workflowId}/executions/{executionId}:
    $ref: "./vro/workflowExecution.yaml#/paths/workflow-execution"

  /workflows/{workflowId}/executions/{executionId}/state:
    $ref: "./vro/workflowExecution.yaml#/paths/workflow-execution-state"

  /workflows/{workflowId}/presentation:
    $ref: "./vro/workflowExecution.yaml#/paths/workflow-presentation"

  /workflows/{workflowId}/presentation/instances:
    $ref: "./vro/workflowExecution.yaml#/paths/workflow-presentation-instances"

  /workflows/{workflowId}/presentation/instances/{presentationExecutionId}:
    $ref: "./vro/workflowExecution.yaml#/paths/workflow-presentation-instance"

### Custom Entities endpoints below ###

  /customEntityTypes:
    $ref: "./vro/customEntities.yaml#/paths/custom-entity-types"

  /customEntityTypes/{customEntityTypeId}:
    $ref: "./vro/customEntities.yaml#/paths/custom-entity-type"

  /customEntityTypes/{customEntityTypeId}/actions:
    $ref: "./vro/customEntities.yaml#/paths/custom-entity-type-actions"

  /customEntityTypes/{customEntityTypeId}/actions/{workflowId}:
    $ref: "./vro/customEntities.yaml#/paths/custom-entity-type-action"

  /customEntities:
    $ref: "./vro/customEntities.yaml#/paths/custom-entities"

  /customEntities/{customEntityId}:
    $ref: "./vro/customEntities.yaml#/paths/custom-entity"

  /customEntities/{customEntityId}/sdkObject:
    $ref: "./vro/customEntities.yaml#/paths/custom-entity-sdk-object"

definitions:
  # Common ErrorType definition for exceptions emerging from openapi endpoints.
  Error:
    $ref: "./common/error.yaml#/definitions/Error"
