# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2017-2018 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************
swagger: "2.0"

info:
  title: Browsing YAML
  description: Base definitions for browsing endpoints
  version: "1.0"

parameters:
  browseScope:
    in: query
    name: scope
    required: false
    schema:
      type: string
    description: The current scope (i.e. parent object) being browsed.  URN format.
  browseFilter:
    in: query
    name: filter
    required: false
    schema:
      type: string
    description: Filter for browsing.  FIQL format.
  browsePage:
    in: query
    name: page
    required: true
    default: 0
    schema:
      type: integer
    description: Page to fetch, zero offset.
  browsePageSize:
    in: query
    name: pageSize
    required: true
    default: 10
    schema:
      type: integer
    description: Results per page to fetch.

definitions:
  BrowseDetails:
    type: object
    properties:
      scope:
        type: string
        description: The scope that was browsed.  URN format.
      filter:
        type: string
        description: The filter used for this query.  FIQL format.
      page:
        type: integer
        description: The page that was fetched, zero-indexed.
      pageSize:
        type: integer
        description: Result count per page that was fetched.

  BrowseResult:
    type: object
    properties:
      id:
        type: string
        description: The URN id of this item.
      name:
        type: string
        description: The human readable name for this item.
      type:
        type: string
        description: The type of this item.
      canSelect:
        type: boolean
        description: Iff this is true, this item can be selected in the browser.
      canBrowse:
        type: boolean
        description: Iff this is true, this item can be browsed by passing it as the scope parameter.

  BrowseResults:
    description: |
      Base browser result, encapsulating result nodes and the query.
    type: object
    properties:
      browse:
        $ref: "#/definitions/BrowseDetails"
      results:
        type: array
        items:
          $ref: "#/definitions/BrowseResult"
      resultTotal:
        type: integer
        description: How many results there are in total (i.e., considering all pages).
      pageCount:
        type: integer
        description: How many pages there are in total.