# *************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2017-2018 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# *************************************************************************
swagger: "2.0"

info:
  title: Entity YAML
  description: Entity reference used to describe VCD entities
  version: "1.0"


definitions:
  EntityReference:
    description: |
      Entity reference used to describe VCD entities
    type: object
    properties:
      name:
        type: string
      id:
        type: string
