# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2017-2018 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************
swagger: "2.0"

info:
  title: Error YAML
  description: Error format of exceptions thrown from openapi endpoints.
  version: "1.0"


definitions:
  Error:
    description: |
      Error type format displayed to users for exceptions emerging from openapi endpoints.
    type: object
    properties:
      minorErrorCode:
        type: string
      message:
        type: string
      stackTrace:
        type: string
    required:
      - minorErrorCode
      - message
