# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2017-2018 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************
swagger: "2.0"

info:
  title: Query YAML
  description: Base definitions for query endpoints
  version: "1.0"

parameters:
  queryFilter:
    in: query
    name: filter
    required: false
    type: string
    default: ""
    description: Filter for a query.  FIQL format.
  querySortAsc:
    in: query
    name: sortAsc
    required: false
    type: string
    default: ""
    description: Field to use for ascending sort
  querySortDesc:
    in: query
    name: sortDesc
    required: false
    type: string
    default: ""
    description: Field to use for descending sort
  queryPage:
    in: query
    name: page
    required: true
    default: 1
    type: integer
    description: Page to fetch, zero offset.
  queryPageSize:
    in: query
    name: pageSize
    required: true
    default: 10
    type: integer
    description: Results per page to fetch.

definitions:
  QueryDetails:
    description: |
      Details about a query that was executed.
    type: object
    properties:
      filter:
        type: string
        description: The filter used for this query.  FIQL format.
      sortAsc:
        type: string
        description: Field used for ascending sort.
      sortDesc:
        type: string
        description: Field used for descending sort.
      page:
        type: integer
        description: The page that was fetched, zero-indexed.
      pageSize:
        type: integer
        description: Result count per page that was fetched.
  QueryResult:
    description: |
      Base query result, just providing a type discriminator.
    discriminator: resultType
    properties:
      resultType:
        type: string
        description: The type of this result.
      value:
        type: object
        description: A single matching result of the query
  QueryResults:
    description: |
      Base query results, encapsulating page information and the query.
    type: object
    properties:
      query:
        $ref: "#/definitions/QueryDetails"
      results:
        type: array
        description: The returned objects from this query.
        items:
           $ref: "#/definitions/QueryResult"
      resultTotal:
        type: integer
        description: How many results there are in total (i.e., considering all pages).
      pageCount:
        type: integer
        description: How many pages there are in total.