# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2011-2018 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************
swagger: "2.0"
info:
  description: |
    Take ownership of the look and feel of your vCloud Director UI.

    System level branding overrides the default vCloud Director branding.

    It defines the styles, logos, and custom links that the UI displays in both
    the system and tenant portals.
  version: "1.0"
  title: Skinning/Branding API

paths:
  logo:
    get:
      tags:
        - branding
      summary: Gets the system level logo
      description: |
        Get the system level logo as raw image data suitable for use in
        an image tag's src attribute.

        If a custom logo is not set then the vCloud Director default logo is
        sent.
      operationId: getSystemLogo
      produces:
        - image/png
        - image/jpeg
        - image/svg+xml
      responses:
        200:
          description: OK
          schema:
            type: string
            format: binary
    put:
      tags:
        - branding
      summary: Sets the system level logo
      description: |
        Set the system logo data.
      operationId: putSystemLogo
      consumes:
        - image/png
        - image/jpeg
        - image/svg+xml
      parameters:
        - name: Content-Type
          in: header
          required: true
        - name: body
          in: body
          required: true
          schema:
            type: string
            format: binary
      responses:
        204:
          description: No Content
        415:
          description: Unsupported Media Type
    delete:
      tags:
        - branding
      summary: Delete system level logo
      description: |
        Delete the system level logo, forcing the get method to return the
        vCloud Director default logo.
      operationId: deleteSystemLogo
      responses:
        204:
          description: No Content

  themes:
    get:
      tags:
        - branding
      summary: Get a list of themes
      description: |
        Get a list of supported themes, uniquely identified by their names.

        This can be used to set the theme in "/branding".
      operationId: getBrandingThemes
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/UiTheme"

  branding:
    get:
      tags:
        - branding
      summary: Gets the system level branding
      description: |
        Get the system level branding information including the portal name,
        portal color, selected theme and custom URLs.
      operationId: getSystemBranding
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/UiBranding"
    put:
      tags:
        - branding
      summary: Sets the system level branding
      description: |
        Sets the system level branding information including the portal name,
        portal color, selected theme and custom URLs.
      operationId: putSystemBranding
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/UiBranding"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/UiBranding"

definitions:
  UiBrandingLink:
    description: |
      A link which can be customized and used in the application.
    type: object
    properties:
      key:
        type: string
      url:
        type: string

  UiTheme:
    description: |
      A theme supported by vCloud Director.
    type: object
    discriminator: themeType
    properties:
      themeType:
        type: string
      name:
        type: string
    required:
      - themeType
      - name

  UiBranding:
    description: |
      A branding object with the portal name, portal color, selected theme and custom URLs.
    type: object
    properties:
      portalName:
        type: string
      portalColor:
        description: |
          A custom color defined by the administrator and used to theme the site.
          The color should be in rgb hex color format such as "FFFFFF" all capitalized.
          Can be set to an empty string to use the selected theme's default colors.
        type: string
      selectedTheme:
        $ref: "#/definitions/UiTheme"
      customLinks:
        type: array
        items:
          $ref: "#/definitions/UiBrandingLink"
